export class LocalRoomNetwork {
  constructor({THREE,scene,status}){this.THREE=THREE;this.scene=scene;this.status=status;this.ws=null;this.id=null;this.room=null;this.host=false;this.config=null;this.connected=false;this.peers=new Map();this.lastInput=0;this.onRoom=null;this.onStart=null;this.onConfig=null;this.onCombat=null;this.onAmmo=null;this.onRespawn=null;this.onSnapshot=null;this.onConnection=null;this.remoteGroup=new THREE.Group();this.remoteGroup.name='RemotePlayers';scene.add(this.remoteGroup);}
  endpoint(){const q=new URLSearchParams(location.search);const explicit=q.get('ws')||window.DUST_MULTIPLAYER_URL||'';if(explicit)return explicit.replace(/^http:/,'ws:').replace(/^https:/,'wss:');if(location.protocol==='https:')return `wss://${location.host}/ws`;if(location.protocol==='http:')return `ws://${location.host}/ws`;return '';}
  connect(){if(this.connected)return Promise.resolve(true);const url=this.endpoint();if(!url) return Promise.reject(new Error('Multiplayer için oyunun Web adresinden açılması gerekiyor.'));
    this.status.textContent='Sunucuya bağlanıyor…';return new Promise((resolve,reject)=>{let done=false;try{this.ws=new WebSocket(url);this.ws.onopen=()=>{this.connected=true;this.status.textContent='Multiplayer sunucusu bağlı.';this.onConnection?.(true);done=true;resolve(true)};this.ws.onerror=()=>{this.status.textContent='Sunucu bağlantı hatası. Tekrar deneniyor…';this.onConnection?.(false);if(!done){done=true;reject(new Error('Multiplayer sunucusuna bağlanılamadı.'))}};this.ws.onclose=()=>{this.connected=false;this.onConnection?.(false);this.status.textContent='Sunucu bağlantısı kesildi. Oda bilgisi korunuyor; yeniden bağlanmayı deneyebilirsin.'};this.ws.onmessage=e=>{try{this.message(JSON.parse(e.data))}catch{}}}catch(e){reject(e)}})}
  send(m){if(this.ws?.readyState===WebSocket.OPEN){this.ws.send(JSON.stringify(m));return true}return false}
  async createRoom(config){await this.connect();this.send({type:'create',config})}
  async joinRoom(code){await this.connect();this.send({type:'join',room:String(code).trim().toUpperCase()})}
  startRoom(config){this.send({type:'start',config})}
  sendInput(input){this.send({type:'input',input})}
  sendFire(f){this.send({type:'fire',...f})}
  sendReload(){this.send({type:'reload'})}
  message(m){if(m.type==='hello'){this.id=m.id;return}if(m.type==='room'){this.id=this.id||m.id;this.room=m.room;this.host=!!m.host;this.config=m.config||this.config;this.status.textContent=`ODA ${this.room} · ${this.host?'HOST':'OYUNCU'} · ${m.count||1} oyuncu`;this.onConfig?.(this.config);this.onRoom?.(m);return}if(m.type==='room-count'){this.onRoom?.({room:this.room,host:this.host,config:this.config,count:m.count});return}if(m.type==='start'){this.config=m.config||this.config;this.onConfig?.(this.config);this.onStart?.(this.config);return}if(m.type==='snapshot'){const players=m.players||[];for(const p of players)this.updatePeer(p);const self=players.find(p=>p.id===this.id);if(self)this.onSnapshot?.(self);return}if(m.type==='combat'){this.onCombat?.(m);return}if(m.type==='ammo'){this.onAmmo?.(m);return}if(m.type==='respawn'){this.onRespawn?.(m);this.updatePeer(m.state);return}if(m.type==='player-left'){this.removePeer(m.id);this.onRoom?.({room:this.room,host:this.host,config:this.config,count:m.count});return}if(m.type==='error')this.status.textContent=`Multiplayer: ${m.message}`}
  makePeer(p){const root=new this.THREE.Group();const bodyMat=new this.THREE.MeshStandardMaterial({color:p.team==='CT'?0x536d83:0x8c623e,roughness:.84});const dark=new this.THREE.MeshStandardMaterial({color:0x1d2326,roughness:.9});const body=new this.THREE.Mesh(new this.THREE.CapsuleGeometry(.3,.72,5,10),bodyMat);body.position.y=.92;const head=new this.THREE.Mesh(new this.THREE.SphereGeometry(.23,12,8),dark);head.position.y=1.58;const weapon=new this.THREE.Mesh(new this.THREE.BoxGeometry(.11,.11,.72),dark);weapon.position.set(.3,1.08,-.34);weapon.rotation.x=Math.PI/2;root.add(body,head,weapon);root.userData.peerId=p.id;this.remoteGroup.add(root);return{root,team:p.team,alive:p.alive};}
  updatePeer(p){if(!p||p.id===this.id)return;let peer=this.peers.get(p.id);if(!peer){peer=this.makePeer(p);this.peers.set(p.id,peer)}peer.root.position.set(p.x,p.y-1.7,p.z);peer.root.rotation.y=p.yaw||0;peer.root.visible=p.alive!==false;peer.team=p.team;peer.alive=p.alive;peer.health=p.health}
  removePeer(id){const p=this.peers.get(id);if(!p)return;this.remoteGroup.remove(p.root);p.root.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});this.peers.delete(id)}
  update(now,state){if(!this.connected)return;if(now-this.lastInput<50)return;this.lastInput=now;const p=state?.player;if(!p)return;this.sendInput({forward:state.forward||0,side:state.side||0,run:!!state.run,yaw:p.ry||0,pitch:p.rx||0,fire:!!state.fire,weapon:state.weapon||'ak'})}
}
export const MultiplayerClient=LocalRoomNetwork;
