export class LocalRoomNetwork {
  constructor({THREE,scene,status}){this.THREE=THREE;this.scene=scene;this.status=status;this.ws=null;this.id=null;this.room=null;this.host=false;this.config=null;this.connected=false;this.peers=new Map();this.lastInput=0;this.pending=null;this.onRoom=null;this.onStart=null;this.onConfig=null;this.onCombat=null;this.onAmmo=null;this.onRespawn=null;this.onSnapshot=null;this.onConnection=null;this.remoteGroup=new THREE.Group();this.remoteGroup.name='RemotePlayers';scene.add(this.remoteGroup);}
  endpoint(){const q=new URLSearchParams(location.search);const explicit=q.get('ws')||window.DUST_MULTIPLAYER_URL||'';if(explicit)return explicit.replace(/^http:/,'ws:').replace(/^https:/,'wss:');if(location.protocol==='https:')return `wss://${location.host}/ws`;if(location.protocol==='http:')return `ws://${location.host}/ws`;return '';}
  connect(){if(this.connected)return Promise.resolve(true);const url=this.endpoint();if(!url)return Promise.reject(new Error('Multiplayer için oyunun Web adresinden açılması gerekiyor.'));this.status.textContent='Sunucuya bağlanıyor…';return new Promise((resolve,reject)=>{let done=false;let timer=setTimeout(()=>{if(done)return;done=true;try{this.ws?.close()}catch{}this.status.textContent='Sunucu bağlantısı zaman aşımına uğradı. Cloudflare Worker /ws adresini kontrol et.';reject(new Error('Sunucuya 10 saniyede bağlanılamadı.'))},10000);try{this.ws=new WebSocket(url);this.ws.onopen=()=>{if(done)return;clearTimeout(timer);this.connected=true;this.status.textContent='Multiplayer sunucusu bağlı.';this.onConnection?.(true);done=true;resolve(true)};this.ws.onerror=()=>{this.status.textContent='Sunucu bağlantı hatası.';this.onConnection?.(false);if(!done){clearTimeout(timer);done=true;reject(new Error('Multiplayer sunucusuna bağlanılamadı.'))}};this.ws.onclose=()=>{clearTimeout(timer);this.connected=false;this.onConnection?.(false);if(!done){done=true;reject(new Error('Multiplayer sunucusu bağlantıyı kapattı.'))}else this.status.textContent='Sunucu bağlantısı kesildi.'};this.ws.onmessage=e=>{try{this.message(JSON.parse(e.data))}catch(err){console.error('Network message error',err)}}}catch(e){clearTimeout(timer);if(!done){done=true;reject(e)}}})}
  send(m){if(this.ws?.readyState===WebSocket.OPEN){this.ws.send(JSON.stringify(m));return true}return false}
  async createRoom(config){await this.connect();if(this.pending)throw new Error('Başka bir oda işlemi devam ediyor.');return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(this.pending?.kind!=='create')return;this.pending=null;reject(new Error('Oda oluşturma zaman aşımına uğradı.'))},10000);this.pending={kind:'create',resolve,reject,timer};if(!this.send({type:'create',config})){clearTimeout(timer);this.pending=null;reject(new Error('Sunucu bağlantısı kapalı.'))}})}
  async joinRoom(code,team){await this.connect();if(this.pending)throw new Error('Başka bir oda işlemi devam ediyor.');const room=String(code).trim().toUpperCase();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(this.pending?.kind!=='join')return;this.pending=null;reject(new Error(`ODA ${room}: Sunucudan cevap gelmedi. /ws Worker bağlantısını kontrol et.`))},10000);this.pending={kind:'join',room,resolve,reject,timer};if(!this.send({type:'join',room,team:team==='CT'?'CT':'T'})){clearTimeout(timer);this.pending=null;reject(new Error('Sunucu bağlantısı kapalı.'))}})}
  startRoom(config){this.send({type:'start',config})}
  sendInput(input){this.send({type:'input',input})}
  sendReload(){this.send({type:'reload'})}
  message(m){if(m.type==='hello'){this.id=m.id;return}if(m.type==='room'){this.id=this.id||m.id;this.room=m.room;this.host=!!m.host;this.config=m.config||this.config;this.status.textContent=`ODA ${this.room} · ${this.host?'HOST':'OYUNCU'} · ${m.count||1} oyuncu`;const cfg={...(this.config||{})};if(m.playerTeam)cfg.team=m.playerTeam;this.onConfig?.(cfg);this.onRoom?.({...m,config:cfg});if(this.pending&&(this.pending.kind==='join'||this.pending.kind==='create')){const p=this.pending;this.pending=null;clearTimeout(p.timer);p.resolve(true)}return}if(m.type==='room-count'){this.onRoom?.({room:this.room,host:this.host,config:this.config,count:m.count});return}if(m.type==='start'){this.config=m.config||this.config;this.onConfig?.(this.config);this.onStart?.(this.config);return}if(m.type==='snapshot'){const players=m.players||[];for(const p of players)this.updatePeer(p);const self=players.find(p=>p.id===this.id);if(self)this.onSnapshot?.(self);return}if(m.type==='combat'){this.onCombat?.(m);return}if(m.type==='reload-start'){this.onReloadStart?.(m);return}if(m.type==='ammo'){this.onAmmo?.(m);return}if(m.type==='respawn'){this.onRespawn?.(m);this.updatePeer(m.state);return}if(m.type==='player-left'){this.removePeer(m.id);this.onRoom?.({room:this.room,host:this.host,config:this.config,count:m.count});return}if(m.type==='error'){const msg=`Multiplayer: ${m.message}`;this.status.textContent=msg;if(this.pending){const p=this.pending;this.pending=null;clearTimeout(p.timer);p.reject(new Error(msg))}}}
  makePeer(p){const root=new this.THREE.Group();const bodyMat=new this.THREE.MeshStandardMaterial({color:p.team==='CT'?0x536d83:0x8c623e,roughness:.84});const dark=new this.THREE.MeshStandardMaterial({color:0x1d2326,roughness:.9});const body=new this.THREE.Mesh(new this.THREE.CapsuleGeometry(.3,.72,5,10),bodyMat);body.position.y=.92;const head=new this.THREE.Mesh(new this.THREE.SphereGeometry(.23,12,8),dark);head.position.y=1.58;const weapon=new this.THREE.Mesh(new this.THREE.BoxGeometry(.11,.11,.72),dark);weapon.position.set(.3,1.08,-.34);weapon.rotation.x=Math.PI/2;root.add(body,head,weapon);root.userData.peerId=p.id;this.remoteGroup.add(root);return{root,team:p.team,alive:p.alive};}
  updatePeer(p){if(!p||p.id===this.id)return;let peer=this.peers.get(p.id);if(!peer){peer=this.makePeer(p);this.peers.set(p.id,peer)}peer.root.position.set(p.x,p.y-1.7,p.z);peer.root.rotation.y=p.yaw||0;peer.root.visible=p.alive!==false;peer.team=p.team;peer.alive=p.alive;peer.health=p.health}
  removePeer(id){const p=this.peers.get(id);if(!p)return;this.remoteGroup.remove(p.root);p.root.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});this.peers.delete(id)}
  update(now,state){if(!this.connected)return;if(now-this.lastInput<50)return;this.lastInput=now;const p=state?.player;if(!p)return;this.sendInput({forward:state.forward||0,side:state.side||0,run:!!state.run,yaw:p.ry||0,pitch:p.rx||0,fire:!!state.fire,weapon:state.weapon||'ak',jump:!!state.jump})}
}
export const MultiplayerClient=LocalRoomNetwork;
