// Dust Operations v10 — Cloudflare Worker + Durable Object.
// One lightweight room service keeps the browser flow simple: connect once,
// then create/join a room by code. Damage, kills and deaths are server-authoritative.
const MAX_PLAYERS=64,TICK=50,WORLD=78,SPEED=4.5,RUN_SPEED=7;
const WEAPONS={
 ak:{damage:34,range:90,interval:.115,spread:.012,magazine:30,reserve:90},m4:{damage:28,range:90,interval:.095,spread:.008,magazine:30,reserve:90},galil:{damage:29,range:88,interval:.105,spread:.011,magazine:35,reserve:105},famas:{damage:27,range:86,interval:.09,spread:.01,magazine:25,reserve:100},mp5:{damage:21,range:62,interval:.07,spread:.022,magazine:30,reserve:120},p90:{damage:20,range:65,interval:.055,spread:.02,magazine:50,reserve:150},xm1014:{damage:18,range:32,interval:.82,spread:.075,magazine:7,reserve:35,pellets:8},scout:{damage:72,range:150,interval:1.05,spread:.002,magazine:10,reserve:60},awp:{damage:115,range:180,interval:1.45,spread:.001,magazine:5,reserve:30},deagle:{damage:48,range:70,interval:.38,spread:.009,magazine:7,reserve:35},pistol:{damage:25,range:65,interval:.28,spread:.006,magazine:12,reserve:60}}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), finite=n=>Number.isFinite(Number(n));
const norm=a=>{let x=Number(a)||0;while(x>Math.PI)x-=Math.PI*2;while(x<-Math.PI)x+=Math.PI*2;return x};
const dir=(y,p)=>{const c=Math.cos(p),s=Math.sin(p);return{x:-Math.sin(y)*c,y:s,z:-Math.cos(y)*c}};
const pub=p=>({id:p.id,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,team:p.team,health:p.health,alive:p.alive,kills:p.kills,deaths:p.deaths,weapon:p.weapon});
const validCode=c=>/^[A-Z0-9]{6}$/.test(c);
const randomCode=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s};

export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/ws'){if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const id=env.ROOMS.idFromName('GLOBAL');return env.ROOMS.get(id).fetch(request)}return env.ASSETS.fetch(request)}};

export class Room{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.players=new Map();this.rooms=new Map();this.timer=null;this.loaded=false}
 async fetch(request){await this.load();const pair=new WebSocketPair();const [client,ws]=Object.values(pair);ws.accept();const p=this.makePlayer(ws);this.players.set(p.id,p);ws.addEventListener('message',e=>this.handle(p.id,e.data));ws.addEventListener('close',()=>this.leave(p.id));this.send(ws,{type:'hello',id:p.id});this.ensureLoop();return new Response(null,{status:101,webSocket:client})}
 async load(){if(this.loaded)return;this.loaded=true;const saved=await this.ctx.storage.get('roomConfigs')||{};for(const [code,config] of Object.entries(saved))this.rooms.set(code,{code,host:null,config,players:new Set(),nextSlot:0,started:true});}
 async persist(){const o={};for(const [c,r] of this.rooms)o[c]=r.config;await this.ctx.storage.put('roomConfigs',o)}
 makePlayer(ws){return{id:crypto.randomUUID(),ws,room:null,team:'T',slot:0,x:-20,y:1.7,z:32,yaw:0,pitch:0,health:100,alive:true,kills:0,deaths:0,weapon:'ak',ammo:Object.fromEntries(Object.entries(WEAPONS).map(([k,w])=>[k,w.magazine])),reserve:Object.fromEntries(Object.entries(WEAPONS).map(([k,w])=>[k,w.reserve])),input:{forward:0,side:0,run:false,yaw:0,pitch:0,fire:false,weapon:'ak'},lastShot:0,respawnAt:0}}
 send(ws,m){try{ws.send(JSON.stringify(m))}catch{}}
 broadcast(r,m,except){for(const id of r.players){const p=this.players.get(id);if(p&&p.ws!==except)this.send(p.ws,m)}}
 ensureLoop(){if(this.timer)return;this.timer=setInterval(()=>this.tick(),TICK)}
 roomFor(p){return p.room?this.rooms.get(p.room):null}
 assign(r,p){let t=0,ct=0;for(const id of r.players){const q=this.players.get(id);if(q?.team==='T')t++;else ct++}p.team=t<=ct?'T':'CT';p.slot=r.nextSlot++;const b=p.team==='T'?{x:-20,z:32,yaw:0}:{x:4,z:-40,yaw:Math.PI};p.x=b.x+(p.slot%4-1.5)*1.25;p.z=b.z+(Math.floor(p.slot/4)%2-.5)*1.25;p.y=1.7;p.yaw=b.yaw;p.pitch=0;p.health=100;p.alive=true}
 async handle(id,raw){let m;try{m=JSON.parse(raw)}catch{return}const p=this.players.get(id);if(!p)return;
  if(m.type==='create'){if(p.room)return;let c=randomCode();while(this.rooms.has(c))c=randomCode();const r={code:c,host:id,config:sanitize(m.config),players:new Set([id]),nextSlot:0,started:true};this.rooms.set(c,r);p.room=c;this.assign(r,p);await this.persist();this.send(p.ws,{type:'room',room:c,host:true,config:r.config,count:1});this.send(p.ws,{type:'start',config:r.config});return}
  if(m.type==='join'){const c=String(m.room||'').trim().toUpperCase(),r=this.rooms.get(c);if(!r)return this.send(p.ws,{type:'error',message:'Oda bulunamadı. Kodun doğru olduğundan emin ol.'});if(r.players.size>=MAX_PLAYERS)return this.send(p.ws,{type:'error',message:'Oda dolu.'});r.players.add(id);p.room=c;this.assign(r,p);this.send(p.ws,{type:'room',room:c,host:false,config:r.config,count:r.players.size});this.send(p.ws,{type:'snapshot',players:[...r.players].map(x=>pub(this.players.get(x))).filter(x=>x&&x.id!==id)});this.broadcast(r,{type:'room-count',count:r.players.size});this.broadcast(r,{type:'start',config:r.config});return}
  const r=this.roomFor(p);if(!r)return;
  if(m.type==='start'&&r.host===id){r.config=sanitize(m.config||r.config);await this.persist();this.broadcast(r,{type:'start',config:r.config});return}
  if(m.type==='input'){const i=m.input||{};p.input.forward=clamp(Number(i.forward)||0,-1,1);p.input.side=clamp(Number(i.side)||0,-1,1);p.input.run=!!i.run;p.input.yaw=finite(i.yaw)?Number(i.yaw):p.yaw;p.input.pitch=finite(i.pitch)?Number(i.pitch):p.pitch;p.input.fire=!!i.fire;p.input.weapon=Object.hasOwn(WEAPONS,i.weapon)?i.weapon:'ak';return}
  if(m.type==='reload'){const w=WEAPONS[p.weapon];if(!w||p.weapon==='knife')return;const have=p.ammo[p.weapon]??0,res=p.reserve[p.weapon]??w.reserve,need=Math.max(0,w.magazine-have),take=Math.min(need,res);p.ammo[p.weapon]=have+take;p.reserve[p.weapon]=res-take;this.send(p.ws,{type:'ammo',id:p.id,weapon:p.weapon,ammo:p.ammo[p.weapon],reserve:p.reserve[p.weapon]});return}
 }
 fire(r,p){if(!p.alive)return;const wid=Object.hasOwn(WEAPONS,p.input.weapon)?p.input.weapon:'ak',w=WEAPONS[wid],now=Date.now();if(now-p.lastShot<w.interval*1000)return;if((p.ammo[wid]??w.magazine)<=0)return;p.lastShot=now;p.weapon=wid;p.ammo[wid]--;const d=dir(p.yaw,p.pitch),o={x:p.x,y:1.45,z:p.z};let best=null,bd=Infinity;for(const id of r.players){const q=this.players.get(id);if(!q||q.id===p.id||!q.alive||q.team===p.team)continue;const vx=q.x-o.x,vy=1.2-o.y,vz=q.z-o.z,dist=Math.hypot(vx,vy,vz);if(dist>w.range)continue;const dot=(vx*d.x+vy*d.y+vz*d.z)/(dist||1),cone=w.spread+Math.min(.07,.28/Math.max(dist,1));if(dot<Math.cos(cone))continue;const px=o.x+d.x*dist,pz=o.z+d.z*dist;if(Math.hypot(q.x-px,q.z-pz)>.62)continue;if(dist<bd){bd=dist;best=q}}
  if(best){let damage=w.damage;if(w.pellets)damage=w.damage*Math.max(1,Math.round(w.pellets*.75));best.health=Math.max(0,best.health-damage);const killed=best.health<=0;if(killed){best.alive=false;best.deaths++;best.respawnAt=now+3000;p.kills++}this.broadcast(r,{type:'combat',attackerId:p.id,targetId:best.id,hit:true,damage,killed,health:best.health,weapon:wid,ox:o.x,oy:o.y,oz:o.z,tx:best.x,ty:1.2,tz:best.z})}else this.broadcast(r,{type:'combat',attackerId:p.id,targetId:null,hit:false,damage:0,killed:false,health:0,weapon:wid,ox:o.x,oy:o.y,oz:o.z,tx:o.x+d.x*w.range,ty:o.y+d.y*w.range,tz:o.z+d.z*w.range})}
 tick(){for(const r of this.rooms.values()){for(const id of r.players){const p=this.players.get(id);if(!p)continue;const now=Date.now();if(!p.alive){if(now>=p.respawnAt){this.assign(r,p);this.broadcast(r,{type:'respawn',id:p.id,state:pub(p)})}continue}const i=p.input,l=Math.hypot(i.forward,i.side)||1,f=i.forward/l,s=i.side/l,speed=i.run?RUN_SPEED:SPEED;p.yaw=norm(i.yaw);p.pitch=clamp(i.pitch,-1.45,1.45);const dt=TICK/1000;p.x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)*speed*dt,-WORLD,WORLD);p.z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)*speed*dt,-WORLD,WORLD);if(i.fire)this.fire(r,p)}this.broadcast(r,{type:'snapshot',players:[...r.players].map(x=>pub(this.players.get(x))).filter(Boolean)})}}
 leave(id){const p=this.players.get(id);if(!p)return;const r=this.roomFor(p);if(r){r.players.delete(id);if(r.host===id){r.host=r.players.values().next().value||null;if(r.host){const h=this.players.get(r.host);this.send(h.ws,{type:'room',room:r.code,host:true,config:r.config,count:r.players.size})}}this.broadcast(r,{type:'player-left',id,count:r.players.size});if(!r.players.size)this.rooms.delete(r.code)}this.players.delete(id)}
}
function sanitize(c){return{team:c?.team==='CT'?'CT':'T',botCount:clamp(Number(c?.botCount)||0,0,64),difficulty:['easy','normal','hard'].includes(c?.difficulty)?c.difficulty:'normal',primary:Object.hasOwn(WEAPONS,c?.primary)?c.primary:'ak'}}
